fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.2.2'
    pe_gem: 'https://github.com/puppetlabs/puppetlabs-pe_gem.git'
    helper: 'https://github.com/bodeco/bodeco_module_helper.git'
    archive:
      repo: 'https://github.com/nanliu/puppet-archive.git'
      ref: 0.1.7
    java: 'https://github.com/bodeco/puppet-java.git'
    windows_env:
      repo: https://github.com/badgerious/puppet-windows-env.git
      ref: 'v2.2.1'
    chocolatey:
      repo: https://github.com/rismoney/puppet-chocolatey.git
      ref: '0.4'
  symlinks:
    gradle: "#{source_dir}"
